### PR TITLE
Fix character-set issues

### PR DESCRIPTION
**Pull request by digitalsparky**
Hi there, I was playing around with your tool, however, it crashes out when there is a character set other than UTF-8.

This patch resolves that issue.
I've included the package dependencies using 'dep' (gopkg lock files included).

### CODE REVIEW

**Comment by fiorix** [comment]
I guess this is the PR you cancelled due to conflicts. You ok with re-opening this?

**Comment by digitalsparky** [comment]
Yup, there you go :).

**Comment by mavogel** [comment]
@digitalsparky thx for the PR. Works fine for non-UTF8 wsdls like https://www.demo.ilias.de/webservice/soap/server.php?wsdl

@fiorix any ETA when this gets merged. I built it locally atm

**Comment by digitalsparky** [comment]
ping @fiorix

**Comment by digitalsparky** [comment]
note: needs to built with GO111MODULE=on env var

**Comment by digitalsparky** [comment]
Fixed, was using go mod but that's not supported in go 1.9, changed to dep.
Also imports pull request #112 as I ran into it when building.

**Comment by digitalsparky** [comment]
Recommend changing to go mod once you deprecate 1.9 support.

**Comment by fiorix** [comment]
👍 

I squashed your commits and merged.

**Comment by digitalsparky** [comment]
Thanks, have a great day!

**Pull request merged**
