### PR TITLE
Fix incorrect using of WSDL methods

### PR DESCRIPTION
**Pull request by artlo**
1) Pass SOAP action as argument to SOAP client, since it's a wrong to use WSDL message parameter name as SOAP action. It may have a few parameters, so the SOAP action is the name of WSDL operation 
2) Fix wsdl function parameter type to use the type name like in WSDL. Before it generated wsdl function with type as WSDL message.name 
3) Fix generating Types with possible Element, to use correct XML.Name The problem was:
- WSDL Messages contains pointer to Element, not the Type, so in generated SOAP operation function incorrect Go type was used (it was not generated and it’s name doesn’t correspond the actual WSDL Type) WSDL: `<operation name="search"> <input name="searchRequest" message="tns:searchRequest"/>   </operation> <message name="searchRequest">         <part name="parameters" element="platformMsgs:search"/>  </message> <element name="search" type="platformMsgs:SearchRequest"/>` Previous version generates the following code: `func (p *PortType) Search(a *Search) (b *SearchResponse, error) type SearchRequest struct {    XMLName      xml.Name xml:»[name space] SearchRequest» }`
- the Go type «**Search**» was not generated
- the Go type «SearchRequest» has the incorrect XMLName. With this changes: `func (p *PortType) Search(a * SearchRequest) (b *SearchResponse, error) type SearchRequest struct {    XMLName      xml.Name xml:»[name space] search» }`

4) XSI namespaces was added + possibility to disable NS in SOAP action header

### CODE REVIEW

**Comment by fiorix** [comment]
This looks ok. Is it backwards compatible tho? I haven't used WSDL in a while so cannot say whether this will break things.

**Comment by artlo** [comment]
No, suddenly I didn't implement backward compatibility. This version generate different SOAP action functions, I just edit SOAP client too, but I think it's not a big deal to implement new method in SOAP client for this new code... If it's needed I will do it.

**Comment by artlo** [comment]
Add backward compatibility for soap client.

**Comment by fiorix** [comment]
Nice. If you don't mind, I will squash these 3 commits before merging. Let me know if you have any concerns, or want to squash it yourself.

**Comment by artlo** [comment]
yes, sure, no problems

**Comment by fiorix** [comment]
👍

**Pull request merged**
